import { updateLock, yarnLockToDatabase } from '../yarn-lock';

describe('yarn1 lock file', () => {
  const lockFile = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

"@babel/runtime-corejs3@^7.10.2":
  version "7.18.9"
  resolved "https://registry.yarnpkg.com/@babel/runtime-corejs3/-/runtime-corejs3-7.18.9.tgz#7bacecd1cb2dd694eacd32a91fcf7021c20770ae"
  integrity sha512-qZEWeccZCrHA2Au4/X05QW5CMdm4VjUDCrGq5gf1ZDcM4hRqreKrtwAn7yci9zfgAS9apvnsFXiGBHBAxZdK9A==
  dependencies:
    core-js-pure "^3.20.2"
    regenerator-runtime "^0.13.4"

"@babel/runtime@^7.10.2", "@babel/runtime@^7.12.5", "@babel/runtime@^7.5.5", "@babel/runtime@^7.9.2":
  version "7.18.9"
  resolved "https://registry.yarnpkg.com/@babel/runtime/-/runtime-7.18.9.tgz#b4fcfce55db3d2e5e080d2490f608a3b9f407f4a"
  integrity sha512-lkqXDcvlFT5rvEjiu6+QYO+1GXrEHRo2LOtS7E4GtX5ESIZOgepqsZBVIj6Pv+a6zqsya9VCgiK1KAK4BvJDAw==
  dependencies:
    regenerator-runtime "^0.13.4"


`;

  it('parses it', () => {
    expect(yarnLockToDatabase(lockFile)).toMatchInlineSnapshot(`
      Object {
        "@babel/runtime": Object {
          "dependencies": Object {
            "regenerator-runtime": "^0.13.4",
          },
        },
        "@babel/runtime-corejs3": Object {
          "dependencies": Object {
            "core-js-pure": "^3.20.2",
            "regenerator-runtime": "^0.13.4",
          },
        },
      }
    `);
  });

  it('wipes it', () => {
    expect(updateLock(lockFile, new Set(['@babel/runtime']))).toMatchInlineSnapshot(`
      "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
      # yarn lockfile v1


      \\"@babel/runtime@^7.10.2\\", \\"@babel/runtime@^7.12.5\\", \\"@babel/runtime@^7.5.5\\", \\"@babel/runtime@^7.9.2\\":
        version \\"7.18.9\\"
        resolved \\"https://registry.yarnpkg.com/@babel/runtime/-/runtime-7.18.9.tgz#b4fcfce55db3d2e5e080d2490f608a3b9f407f4a\\"
        integrity sha512-lkqXDcvlFT5rvEjiu6+QYO+1GXrEHRo2LOtS7E4GtX5ESIZOgepqsZBVIj6Pv+a6zqsya9VCgiK1KAK4BvJDAw==
        dependencies:
          regenerator-runtime \\"^0.13.4\\"
      "
    `);
  });
});
