import { updateLock, yarnLockToDatabase } from '../yarn-lock';

describe('yarn2 lock file', () => {
  const lockFile = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 5
  cacheKey: 8

"@ampproject/remapping@npm:^2.0.0":
  version: 2.0.2
  resolution: "@ampproject/remapping@npm:2.0.2"
  dependencies:
    "@jridgewell/trace-mapping": ^0.2.2
    sourcemap-codec: 1.4.8
  checksum: 5759df3715f0291cbf97099a9bb7202201a1a267e232ee1505418c768b9ae7281cd550b1da563a12808a06529eb1298744a6cabde21ac354fc8450044c7f2213
  languageName: node
  linkType: hard

"@babel/runtime@npm:^7.0.0, @babel/runtime@npm:^7.10.0, @babel/runtime@npm:^7.10.2, @babel/runtime@npm:^7.12.0, @babel/runtime@npm:^7.12.1, @babel/runtime@npm:^7.12.13, @babel/runtime@npm:^7.12.5, @babel/runtime@npm:^7.13.10, @babel/runtime@npm:^7.14.0, @babel/runtime@npm:^7.14.8, @babel/runtime@npm:^7.16.3, @babel/runtime@npm:^7.3.1, @babel/runtime@npm:^7.5.0, @babel/runtime@npm:^7.5.5, @babel/runtime@npm:^7.7.2, @babel/runtime@npm:^7.7.6, @babel/runtime@npm:^7.8.4, @babel/runtime@npm:^7.8.7, @babel/runtime@npm:^7.9.2":
  version: 7.16.5
  resolution: "@babel/runtime@npm:7.16.5"
  dependencies:
    regenerator-runtime: ^0.13.4
  checksum: b96e67280efe581c6147b4fe984dfe08a8fbea048934a092f3cbf4dcf61725f6b221cb0c879b6e6e98671f83a104c9e8cfbd24c683e5ebcc886a731aa8984ad0
  languageName: node
  linkType: hard
`;

  it('parses it', () => {
    expect(yarnLockToDatabase(lockFile)).toMatchInlineSnapshot(`
      Object {
        "@ampproject/remapping": Object {
          "dependencies": Object {
            "@jridgewell/trace-mapping": "^0.2.2",
            "sourcemap-codec": "1.4.8",
          },
        },
        "@babel/runtime": Object {
          "dependencies": Object {
            "regenerator-runtime": "^0.13.4",
          },
        },
      }
    `);
  });

  it('wipes it', () => {
    expect(updateLock(lockFile, new Set(['@babel/runtime']))).toMatchInlineSnapshot(`
      "# This file is generated by running \\"yarn install\\" inside your project.
      # Manual changes might be lost - proceed with caution!

      __metadata:
        version: 5
        cacheKey: 8

      \\"@babel/runtime@npm:^7.0.0, @babel/runtime@npm:^7.10.0, @babel/runtime@npm:^7.10.2, @babel/runtime@npm:^7.12.0, @babel/runtime@npm:^7.12.1, @babel/runtime@npm:^7.12.13, @babel/runtime@npm:^7.12.5, @babel/runtime@npm:^7.13.10, @babel/runtime@npm:^7.14.0, @babel/runtime@npm:^7.14.8, @babel/runtime@npm:^7.16.3, @babel/runtime@npm:^7.3.1, @babel/runtime@npm:^7.5.0, @babel/runtime@npm:^7.5.5, @babel/runtime@npm:^7.7.2, @babel/runtime@npm:^7.7.6, @babel/runtime@npm:^7.8.4, @babel/runtime@npm:^7.8.7, @babel/runtime@npm:^7.9.2\\":
        version: 7.16.5
        resolution: \\"@babel/runtime@npm:7.16.5\\"
        dependencies:
          regenerator-runtime: ^0.13.4
        checksum: b96e67280efe581c6147b4fe984dfe08a8fbea048934a092f3cbf4dcf61725f6b221cb0c879b6e6e98671f83a104c9e8cfbd24c683e5ebcc886a731aa8984ad0
        languageName: node
        linkType: hard
      "
    `);
  });

  it('persist it', () => {
    expect(updateLock(lockFile, new Set(yarnLockToDatabase(lockFile).map(([name]) => name)))).toBe(lockFile);
  });
});
